package com.example.client.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_ASSET,
    DELETE_ASSET,
    GET_ASSET,
    GETALL_ASSET,
    UPDATE_ASSET,
    SEARCH_ASSET,
    ADD_ROLE,
    DELETE_ROLE,
    GET_ROLE,
    GETALL_ROLES,
    UPDATE_ROLE,
    CALCULATE_AMORTIZATION,
    GETALL_AMORTIZATION,
    SAVE_REPORT,
    SORT_ASSET,
    ADD_USER,
    DELETE_USER,
    GET_USER,
    GETALL_USERS,
    UPDATE_USER,
    SEND_MESSAGE,
    GET_MESSAGES, MARK_AS_READ
}
