package com.example.server.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_ASSET,
    DELETE_ASSET,
    GET_ASSET,
    GETALL_ASSET,
    UPDATE_ASSET,
    SEARCH_ASSET,
    SORT_ASSET,
    CALCULATE_AMORTIZATION,
    GETALL_AMORTIZATION,
    ADD_ROLE,
    DELETE_ROLE,
    GET_ROLE,
    GETALL_ROLES,
    UPDATE_ROLE,
    ADD_USER,
    DELETE_USER,
    GET_USER,
    GETALL_USERS,
    UPDATE_USER
}
